config/routes.rb
Rails.application.routes.draw do
  get 'products/index'
  get 'products/search'
  root to: 'products#index'
  get 'products/search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :products
  
end

app/models/product.rb
class Product < ApplicationRecord

  belongs_to :category
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :search_product, only: [:index, :search]
  
  def index
    @products = Product.all
    set_product_column
    set_category_column
  end

  def search
    @results = @p.result.includes(:category) # 検索条件にマッチした商品の情報を取得
  end

  private

  def search_product
    @p = Product.ransack(params[:q])  # 検索オブジェクトを生成

  end

  def set_product_column
    @product_name = Product.select("name").distinct # 重複なくnameカラムのデータを取り出す
    @product_size = Product.select("size").distinct
    @product_status = Product.select("status").distinct
  end

  def set_category_column
    @category_name = Category.select("name").distinct
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>
  商品検索
</h1>
<%= search_form_for @p , url: products_search_path do |f| %>
  <%= f.label :name_eq, '商品名' %>
  <%= f.collection_select :name_eq, @product_name, :name, :name, include_blank: '指定なし'%>
  <br>
  <%= f.label :size_eq, 'サイズ：' %>
  <%= f.collection_select :size_eq, @product_size, :size, :size, include_blank: '指定なし'%>
  <br>
  <%= f.label :status_eq, '商品状態：' %>
    <%= f.collection_select :status_eq, @product_status, :status, :status, include_blank: '指定なし'%>
    <br>
    <%= f.label :category_name_eq, 'カテゴリー：' %>
    <%= f.collection_select :category_name_eq, @category_name, :name, :name, include_blank: '指定なし' %>
    <br>
    <%= f.label :price, '価格：'%>
    <%= f.radio_button :price_lteq, '' %>
    指定なし
    <%= f.radio_button :price_lteq, '1000'%>
    1000円以下
    <%= f.radio_button :price_lteq, '2500' %>
    2500円以下
    <%= f.radio_button :price_lteq, '5000' %>
    5000円以下
  <br>
  <%= f.submit '検索' %>
  <br>
  <%# 商品一覧 %>
  <% @products.each do |product| %>
  <td>
  <br>
  <li>
    <%= product.name %>
    <%= product.size %>
    <%= product.status %>
    <%= product.price %>
    <%= product.category.name %>
  </li>
  <% end %>
<% end %>

app/views/products/search.html.erb
<h1>
  検索結果
</h1>
<%# 検索結果の個数で条件分岐 %>
<% if @results.length != 0 %>
  <% @results.each do |result| %>
    <td>
    <br>
    <li>
      <%= result.name %>
      <%= result.size %>
      <%= result.status %>
      <%= result.price %>
      <%= result.category.name %>
    </li>
  <% end %>
<% else %>
  該当する商品はありません
<% end %>
<br>
<%= link_to 'トップページへ戻る', root_path %>